### ISSUE TITLE
Sortable with textareas

### ISSUE THREAD

**Issue by juliocorral** [aewebsolutions/clayfy#1]
Hi,

I'm trying to sort several textareas inside a form using your plugin. I've a administration panel and users can add textareas dinamically. 
I need users to sort the textareas and keep them editable. Could you send and example on Codepen or JSfiddle. When I use the plugin textareas don´t be editable.

Thank you in advance!!

**Comment by aewebsolutions** [comment]
Hi!
See options: https://github.com/aewebsolutions/clayfy#draggable-1
You have to wrap your textarea and exclude it with `not` option.

```html
<div class="wrapper">
    <textarea></textarea>
</div>
```
```javascript
$('.wrapper').clayfy({not: 'textarea'});
```
Some part of wrapper element must be visible to user, because only wrapper will be draggable (not its child `textarea`)

**Comment by juliocorral** [comment]
Thank you!!!!

2016-11-21 17:49 GMT+01:00 aewebsolutions notifications@github.com:
